### ISSUE TITLE
Moogoose promise problem with build 3a4612b 

### ISSUE THREAD

**Issue by SaschaAlex** [Misterjo/I-did-it-reddit#18]
Commit 3a4612b is currently failing to run when a user write a command . The problem seems to be from the method [requestFromMessage](https://github.com/Misterjo/I-did-it-reddit/blob/3a4612b9bad359e2699b7242d0d3be0645337179/src/commands/commandRequest.js). This method calls [createUser](https://github.com/Misterjo/I-did-it-reddit/blob/3a4612b9bad359e2699b7242d0d3be0645337179/src/database/Database.js).
The bug seems to be related to some bad promise handling of some  mongoose promise. A documentation of Mongoose promise can be find at this [link](https://mongoosejs.com/docs/promises.html).

Here the log 
```js
E:\Documents\RandomProject\I-did-it-reddit\src\bot\CommandListener.js:7
        switch (request.command.head) {
                        ^

TypeError: Cannot read property 'command' of undefined
    at new CommandListener (E:\Documents\RandomProject\I-did-it-reddit\src\bot\CommandListener.js:7:25)
    at Client.<anonymous> (E:\Documents\RandomProject\I-did-it-reddit\src\bot\Bot.js:39:17)
    at Client.emit (events.js:376:20)
    at MessageCreateAction.handle (E:\Documents\RandomProject\I-did-it-reddit\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (E:\Documents\RandomProject\I-did-it-reddit\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (E:\Documents\RandomProject\I-did-it-reddit\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (E:\Documents\RandomProject\I-did-it-reddit\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (E:\Documents\RandomProject\I-did-it-reddit\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (E:\Documents\RandomProject\I-did-it-reddit\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:376:20)
    at Receiver.receiverOnMessage (E:\Documents\RandomProject\I-did-it-reddit\node_modules\ws\lib\websocket.js:833:20)
    at Receiver.emit (events.js:376:20)
    at Receiver.dataMessage (E:\Documents\RandomProject\I-did-it-reddit\node_modules\ws\lib\receiver.js:517:14)  
    at Receiver.getData (E:\Documents\RandomProject\I-did-it-reddit\node_modules\ws\lib\receiver.js:435:17)      
    at Receiver.startLoop (E:\Documents\RandomProject\I-did-it-reddit\node_modules\ws\lib\receiver.js:143:22)    
    at Receiver._write (E:\Documents\RandomProject\I-did-it-reddit\node_modules\ws\lib\receiver.js:78:10) 
```
```js

        //Message listener
        this.client.on('message', message => {
            let [prefix, ...command] = message.content;
            if (prefix == this.config.prefix) {
                 
                Database.createUser(message).then((user) => {
                    console.log(user);
                });
                
                //CommandRequest.requestFromMessage(message);

                //new CommandListener(message);
            }
        })
    }

}
```
This code seems to be working just fine which is odd.

**Comment by SaschaAlex** [comment]
Fixed in https://github.com/Misterjo/I-did-it-reddit/commit/df7ff7ca1623b83584b94ab247bc485ce0127403
